language: php
dist: trusty
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
before_script:
  - composer install
script:
  - php -v
  #- phpunit --version #fails on 7.2
  - vendor/bin/codecept --version
  - vendor/bin/codecept run unit --coverage --coverage-xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
